// Constants for schedule rebalance functionality
// Extracted from ScheduleRebalanceModal.tsx

import type { Weekday, TimezoneOption } from "./types";

export const WEEKDAYS: Weekday[] = [
  { value: 1, label: 'Monday' },
  { value: 2, label: 'Tuesday' },
  { value: 3, label: 'Wednesday' },
  { value: 4, label: 'Thursday' },
  { value: 5, label: 'Friday' },
  { value: 6, label: 'Saturday' },
  { value: 0, label: 'Sunday' },
];

// Comprehensive timezone list grouped by region
export const TIMEZONE_GROUPS: Record<string, TimezoneOption[]> = {
  'North America': [
    { value: 'America/New_York', label: 'New York (Eastern)' },
    { value: 'America/Chicago', label: 'Chicago (Central)' },
    { value: 'America/Denver', label: 'Denver (Mountain)' },
    { value: 'America/Phoenix', label: 'Phoenix (Arizona)' },
    { value: 'America/Los_Angeles', label: 'Los Angeles (Pacific)' },
    { value: 'America/Anchorage', label: 'Anchorage (Alaska)' },
    { value: 'Pacific/Honolulu', label: 'Honolulu (Hawaii)' },
    { value: 'America/Toronto', label: 'Toronto' },
    { value: 'America/Vancouver', label: 'Vancouver' },
    { value: 'America/Mexico_City', label: 'Mexico City' },
  ],
  'South America': [
    { value: 'America/Sao_Paulo', label: 'São Paulo' },
    { value: 'America/Buenos_Aires', label: 'Buenos Aires' },
    { value: 'America/Lima', label: 'Lima' },
    { value: 'America/Bogota', label: 'Bogotá' },
    { value: 'America/Santiago', label: 'Santiago' },
    { value: 'America/Caracas', label: 'Caracas' },
  ],
  'Europe': [
    { value: 'Europe/London', label: 'London' },
    { value: 'Europe/Paris', label: 'Paris' },
    { value: 'Europe/Berlin', label: 'Berlin' },
    { value: 'Europe/Madrid', label: 'Madrid' },
    { value: 'Europe/Rome', label: 'Rome' },
    { value: 'Europe/Amsterdam', label: 'Amsterdam' },
    { value: 'Europe/Brussels', label: 'Brussels' },
    { value: 'Europe/Vienna', label: 'Vienna' },
    { value: 'Europe/Stockholm', label: 'Stockholm' },
    { value: 'Europe/Oslo', label: 'Oslo' },
    { value: 'Europe/Copenhagen', label: 'Copenhagen' },
    { value: 'Europe/Helsinki', label: 'Helsinki' },
    { value: 'Europe/Athens', label: 'Athens' },
    { value: 'Europe/Istanbul', label: 'Istanbul' },
    { value: 'Europe/Moscow', label: 'Moscow' },
    { value: 'Europe/Warsaw', label: 'Warsaw' },
    { value: 'Europe/Prague', label: 'Prague' },
    { value: 'Europe/Budapest', label: 'Budapest' },
    { value: 'Europe/Zurich', label: 'Zurich' },
    { value: 'Europe/Dublin', label: 'Dublin' },
    { value: 'Europe/Lisbon', label: 'Lisbon' },
  ],
  'Asia': [
    { value: 'Asia/Tokyo', label: 'Tokyo' },
    { value: 'Asia/Shanghai', label: 'Shanghai' },
    { value: 'Asia/Hong_Kong', label: 'Hong Kong' },
    { value: 'Asia/Singapore', label: 'Singapore' },
    { value: 'Asia/Seoul', label: 'Seoul' },
    { value: 'Asia/Taipei', label: 'Taipei' },
    { value: 'Asia/Bangkok', label: 'Bangkok' },
    { value: 'Asia/Jakarta', label: 'Jakarta' },
    { value: 'Asia/Manila', label: 'Manila' },
    { value: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur' },
    { value: 'Asia/Mumbai', label: 'Mumbai' },
    { value: 'Asia/Kolkata', label: 'Kolkata' },
    { value: 'Asia/Delhi', label: 'New Delhi' },
    { value: 'Asia/Bangalore', label: 'Bangalore' },
    { value: 'Asia/Dubai', label: 'Dubai' },
    { value: 'Asia/Tel_Aviv', label: 'Tel Aviv' },
    { value: 'Asia/Jerusalem', label: 'Jerusalem' },
    { value: 'Asia/Riyadh', label: 'Riyadh' },
    { value: 'Asia/Kuwait', label: 'Kuwait' },
    { value: 'Asia/Qatar', label: 'Doha' },
    { value: 'Asia/Karachi', label: 'Karachi' },
    { value: 'Asia/Dhaka', label: 'Dhaka' },
    { value: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh City' },
  ],
  'Africa': [
    { value: 'Africa/Cairo', label: 'Cairo' },
    { value: 'Africa/Lagos', label: 'Lagos' },
    { value: 'Africa/Johannesburg', label: 'Johannesburg' },
    { value: 'Africa/Nairobi', label: 'Nairobi' },
    { value: 'Africa/Casablanca', label: 'Casablanca' },
    { value: 'Africa/Algiers', label: 'Algiers' },
    { value: 'Africa/Tunis', label: 'Tunis' },
  ],
  'Oceania': [
    { value: 'Australia/Sydney', label: 'Sydney' },
    { value: 'Australia/Melbourne', label: 'Melbourne' },
    { value: 'Australia/Brisbane', label: 'Brisbane' },
    { value: 'Australia/Perth', label: 'Perth' },
    { value: 'Australia/Adelaide', label: 'Adelaide' },
    { value: 'Pacific/Auckland', label: 'Auckland' },
    { value: 'Pacific/Fiji', label: 'Fiji' },
  ],
};